// Stub for PebbleKit JS's `require('message_keys')` module, used only by
// the host-side pack.js tests (tests/pack.test.js). Mirrors the real
// generated build/js/message_keys.json (regenerated by `pebble build` from
// package.json's messageKeys array) so key names match, but the numeric
// values themselves don't need to match exactly - pack.js only uses them as
// opaque dictionary keys.
//
// Usage: NODE_PATH="$(pwd)/tests/js" node tests/pack.test.js
module.exports = {
  MSG_TYPE: 10000,
  SCHEMA: 10001,
  UNIT_SYSTEM: 10002,
  TEMP_C10: 10003,
  FEELS_C10: 10004,
  HI_C10: 10005,
  LO_C10: 10006,
  HUMIDITY: 10007,
  WIND_KMH10: 10008,
  WIND_DIR: 10009,
  WX_CODE: 10010,
  IS_DAY: 10011,
  PRESS_HPA10: 10012,
  PRESS_SERIES: 10013,
  PRESS_NOW_IDX: 10014,
  PRESS_T0_UTC: 10015,
  SUNRISE_UTC: 10016,
  SUNSET_UTC: 10017,
  UPDATED_UTC: 10018,
  LOC_NAME: 10019,
  LAT_SIGN: 10020,
  ERR_CODE: 10021,
  REQUEST: 10022,
  PKJS_READY: 10023,
  TEMP_SERIES: 10024,
  WX_SERIES: 10025,
  DAILY_HI: 10026,
  DAILY_LO: 10027,
  DAILY_CODE: 10028,
  DAILY_T0_UTC: 10029,
  PLACE_CHANGE: 10030,
  PRESS_DELTA3: 10031,
  SAMPLE_HRS: 10032,
};
